// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("FSharp.Object.Diff")>]
[<assembly: AssemblyProductAttribute("FSharp.Obejct.Diff")>]
[<assembly: InternalsVisibleToAttribute("FSharp.Object.Diff.Tests")>]
[<assembly: AssemblyVersionAttribute("0.11.0")>]
[<assembly: AssemblyFileVersionAttribute("0.11.0")>]
[<assembly: AssemblyInformationalVersionAttribute("0.11.0-alpha1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FSharp.Object.Diff"
    let [<Literal>] AssemblyProduct = "FSharp.Obejct.Diff"
    let [<Literal>] InternalsVisibleTo = "FSharp.Object.Diff.Tests"
    let [<Literal>] AssemblyVersion = "0.11.0"
    let [<Literal>] AssemblyFileVersion = "0.11.0"
    let [<Literal>] AssemblyInformationalVersion = "0.11.0-alpha1"
