module FSharp.Object.Diff.Tests.PrimitiveDifferTest

open System
open Persimmon
open UseTestNameByReflection
open Foq
open FSharp.Object.Diff

let setup (f: Mock<_> -> Mock<_>) =
  let target =
    Mock<PrimitiveDefaultValueModeResolver>()
    |> f
  PrimitiveDiffer(target.Create())

let ``detects state based on the given PrimitiveDefaultValueMode`` = parameterize {
  source [
    (UnAssigned, typeof<sbyte>, box 0uy, box 0uy, box 0uy, Untouched)
    (UnAssigned, typeof<sbyte>, box 0uy, box 1uy, box 0uy, Added)
    (UnAssigned, typeof<sbyte>, box 1uy, box 0uy, box 0uy, Removed)
    (UnAssigned, typeof<sbyte>, box 1uy, box 2uy, box 0uy, Changed)
    (UnAssigned, typeof<sbyte>, box 2uy, box 2uy, box 0uy, Untouched)
    (UnAssigned, typeof<uint16>, box 0us, box 0us, box 0us, Untouched)
    (UnAssigned, typeof<uint16>, box 0us, box 1us, box 0us, Added)
    (UnAssigned, typeof<uint16>, box 1us, box 0us, box 0us, Removed)
    (UnAssigned, typeof<uint16>, box 1us, box 2us, box 0us, Changed)
    (UnAssigned, typeof<uint16>, box 2us, box 2us, box 0us, Untouched)
    (UnAssigned, typeof<uint32>, box 0u, box 0u, box 0u, Untouched)
    (UnAssigned, typeof<uint32>, box 0u, box 1u, box 0u, Added)
    (UnAssigned, typeof<uint32>, box 1u, box 0u, box 0u, Removed)
    (UnAssigned, typeof<uint32>, box 1u, box 2u, box 0u, Changed)
    (UnAssigned, typeof<uint32>, box 2u, box 2u, box 0u, Untouched)
    (UnAssigned, typeof<uint64>, box 0UL, box 0UL, box 0UL, Untouched)
    (UnAssigned, typeof<uint64>, box 0UL, box 1UL, box 0UL, Added)
    (UnAssigned, typeof<uint64>, box 1UL, box 0UL, box 0UL, Removed)
    (UnAssigned, typeof<uint64>, box 1UL, box 2UL, box 0UL, Changed)
    (UnAssigned, typeof<uint64>, box 2UL, box 2UL, box 0UL, Untouched)
    (UnAssigned, typeof<byte>, box 0y, box 0y, box 0y, Untouched)
    (UnAssigned, typeof<byte>, box 0y, box 1y, box 0y, Added)
    (UnAssigned, typeof<byte>, box 1y, box 0y, box 0y, Removed)
    (UnAssigned, typeof<byte>, box 1y, box 2y, box 0y, Changed)
    (UnAssigned, typeof<byte>, box 2y, box 2y, box 0y, Untouched)
    (UnAssigned, typeof<int16>, box 0s, box 0s, box 0s, Untouched)
    (UnAssigned, typeof<int16>, box 0s, box 1s, box 0s, Added)
    (UnAssigned, typeof<int16>, box 1s, box 0s, box 0s, Removed)
    (UnAssigned, typeof<int16>, box 1s, box 2s, box 0s, Changed)
    (UnAssigned, typeof<int16>, box 2s, box 2s, box 0s, Untouched)
    (UnAssigned, typeof<int>, box 0, box 0, box 0, Untouched)
    (UnAssigned, typeof<int>, box 0, box 1, box 0, Added)
    (UnAssigned, typeof<int>, box 1, box 0, box 0, Removed)
    (UnAssigned, typeof<int>, box 1, box 2, box 0, Changed)
    (UnAssigned, typeof<int>, box 2, box 2, box 0, Untouched)
    (UnAssigned, typeof<int64>, box 0L, box 0L, box 0L, Untouched)
    (UnAssigned, typeof<int64>, box 0L, box 1L, box 0L, Added)
    (UnAssigned, typeof<int64>, box 1L, box 0L, box 0L, Removed)
    (UnAssigned, typeof<int64>, box 1L, box 2L, box 0L, Changed)
    (UnAssigned, typeof<int64>, box 2L, box 2L, box 0L, Untouched)
    (UnAssigned, typeof<float32>, box 0.0f, box 0.0f, box 0.0f, Untouched)
    (UnAssigned, typeof<float32>, box 0.0f, box 1.0f, box 0.0f, Added)
    (UnAssigned, typeof<float32>, box 1.0f, box 0.0f, box 0.0f, Removed)
    (UnAssigned, typeof<float32>, box 1.0f, box 2.0f, box 0.0f, Changed)
    (UnAssigned, typeof<float32>, box 2.0f, box 2.0f, box 0.0f, Untouched)
    (UnAssigned, typeof<float>, box 0.0, box 0.0, box 0.0, Untouched)
    (UnAssigned, typeof<float>, box 0.0, box 1.0, box 0.0, Added)
    (UnAssigned, typeof<float>, box 1.0, box 0.0, box 0.0, Removed)
    (UnAssigned, typeof<float>, box 1.0, box 2.0, box 0.0, Changed)
    (UnAssigned, typeof<float>, box 2.0, box 2.0, box 0.0, Untouched)
    (UnAssigned, typeof<bool>, box false, box false, box false, Untouched)
    (UnAssigned, typeof<bool>, box false, box true, box false, Added)
    (UnAssigned, typeof<bool>, box true, box false, box false, Removed)
    (UnAssigned, typeof<bool>, box true, box true, box false, Untouched)
    (Assigned, typeof<sbyte>, box 0uy, box 0uy, box 0uy, Untouched)
    (Assigned, typeof<sbyte>, box 0uy, box 1uy, box 0uy, Changed)
    (Assigned, typeof<sbyte>, box 1uy, box 0uy, box 0uy, Changed)
    (Assigned, typeof<sbyte>, box 1uy, box 2uy, box 0uy, Changed)
    (Assigned, typeof<sbyte>, box 2uy, box 2uy, box 0uy, Untouched)
    (Assigned, typeof<uint16>, box 0us, box 0us, box 0us, Untouched)
    (Assigned, typeof<uint16>, box 0us, box 1us, box 0us, Changed)
    (Assigned, typeof<uint16>, box 1us, box 0us, box 0us, Changed)
    (Assigned, typeof<uint16>, box 1us, box 2us, box 0us, Changed)
    (Assigned, typeof<uint16>, box 2us, box 2us, box 0us, Untouched)
    (Assigned, typeof<uint32>, box 0u, box 0u, box 0u, Untouched)
    (Assigned, typeof<uint32>, box 0u, box 1u, box 0u, Changed)
    (Assigned, typeof<uint32>, box 1u, box 0u, box 0u, Changed)
    (Assigned, typeof<uint32>, box 1u, box 2u, box 0u, Changed)
    (Assigned, typeof<uint32>, box 2u, box 2u, box 0u, Untouched)
    (Assigned, typeof<uint64>, box 0UL, box 0UL, box 0UL, Untouched)
    (Assigned, typeof<uint64>, box 0UL, box 1UL, box 0UL, Changed)
    (Assigned, typeof<uint64>, box 1UL, box 0UL, box 0UL, Changed)
    (Assigned, typeof<uint64>, box 1UL, box 2UL, box 0UL, Changed)
    (Assigned, typeof<uint64>, box 2UL, box 2UL, box 0UL, Untouched)
    (Assigned, typeof<byte>, box 0y, box 0y, box 0y, Untouched)
    (Assigned, typeof<byte>, box 0y, box 1y, box 0y, Changed)
    (Assigned, typeof<byte>, box 1y, box 0y, box 0y, Changed)
    (Assigned, typeof<byte>, box 1y, box 2y, box 0y, Changed)
    (Assigned, typeof<byte>, box 2y, box 2y, box 0y, Untouched)
    (Assigned, typeof<int16>, box 0s, box 0s, box 0s, Untouched)
    (Assigned, typeof<int16>, box 0s, box 1s, box 0s, Changed)
    (Assigned, typeof<int16>, box 1s, box 0s, box 0s, Changed)
    (Assigned, typeof<int16>, box 1s, box 2s, box 0s, Changed)
    (Assigned, typeof<int16>, box 2s, box 2s, box 0s, Untouched)
    (Assigned, typeof<int>, box 0, box 0, box 0, Untouched)
    (Assigned, typeof<int>, box 0, box 1, box 0, Changed)
    (Assigned, typeof<int>, box 1, box 0, box 0, Changed)
    (Assigned, typeof<int>, box 1, box 2, box 0, Changed)
    (Assigned, typeof<int>, box 2, box 2, box 0, Untouched)
    (Assigned, typeof<int64>, box 0L, box 0L, box 0L, Untouched)
    (Assigned, typeof<int64>, box 0L, box 1L, box 0L, Changed)
    (Assigned, typeof<int64>, box 1L, box 0L, box 0L, Changed)
    (Assigned, typeof<int64>, box 1L, box 2L, box 0L, Changed)
    (Assigned, typeof<int64>, box 2L, box 2L, box 0L, Untouched)
    (Assigned, typeof<float32>, box 0.0f, box 0.0f, box 0.0f, Untouched)
    (Assigned, typeof<float32>, box 0.0f, box 1.0f, box 0.0f, Changed)
    (Assigned, typeof<float32>, box 1.0f, box 0.0f, box 0.0f, Changed)
    (Assigned, typeof<float32>, box 1.0f, box 2.0f, box 0.0f, Changed)
    (Assigned, typeof<float32>, box 2.0f, box 2.0f, box 0.0f, Untouched)
    (Assigned, typeof<float>, box 0.0, box 0.0, box 0.0, Untouched)
    (Assigned, typeof<float>, box 0.0, box 1.0, box 0.0, Changed)
    (Assigned, typeof<float>, box 1.0, box 0.0, box 0.0, Changed)
    (Assigned, typeof<float>, box 1.0, box 2.0, box 0.0, Changed)
    (Assigned, typeof<float>, box 2.0, box 2.0, box 0.0, Untouched)
    (Assigned, typeof<bool>, box false, box false, box false, Untouched)
    (Assigned, typeof<bool>, box false, box true, box false, Changed)
    (Assigned, typeof<bool>, box true, box false, box false, Changed)
    (Assigned, typeof<bool>, box true, box true, box false, Untouched)
  ]
  run (fun (mode, typ, base_, working, fresh, state) -> test {
    let target = setup (fun target ->
      target.SetupMethod(fun x -> <@ x.ResolvePrimitiveDefaultValueMode @>).Returns(mode)
    )
    let accessor = Mock<TypeAwareAccessor>().Setup(fun x -> <@ x.Type @>).Returns(typ).Create()
    let instances = Instances.Of(accessor, working, base_, fresh)
    let node = target.Compare(DiffNode.Root, instances)
    do! assertEquals state node.State
  })
}
